### PR TITLE
Be more strict - pass through expressions not explicitly covered by this ppx

### PR DESCRIPTION
**Pull request by hcarty**
In some cases unhandled extension points may be silently ignored.

This builds on top of #8 - I can rebase this PR once/if that one is merged.

### CODE REVIEW

**Comment by zepalmer** [comment]
I may have a misconception as to how the OCaml PPX system works here.  I was under the impression that each PPX processor was executed as a separate subprocess and, as a result, any unprocessed extensions will be handled by the next PPX extension in the chain.  Is this not true?  I know that there have been some efforts to make PPX processors which perform composite operations (e.g. [`ppx_driver`](https://github.com/janestreet/ppx_driver) by Jane Street).  Or do I misunderstand the code committed here?

**Comment by hcarty** [comment]
That's mostly true.  The results of one ppx will be passed to the next.  So if `ocaml-monadic` is the first ppx in line then its output will be passed to the next ppx for processing (or to the compiler if there is no next ppx).  In the case of ocaml-migrate-parsetree, ppx_driver or any other ppx-composing tools, the same thing happens but a of the ppx passes exist and occur within a single process rather than serializing the results from one process into another.

This means that any extension points or attributes that are dropped from the AST by a ppx will not be available to subsequent ppx passes.

**Comment by hcarty** [comment]
I rebased on `master` so this should be easier to read and review now!

**Comment by hcarty** [comment]
Thank you for all of the detailed responses and quick reviews!

**Comment by zepalmer** [comment]
Excellent!  I didn't realize that ocaml-migrate-parsetree was performing this kind of compositional transformation.  Thanks for catching this before release.  I should definitely push a new version to OPAM that has the new extensions you've implemented.

Thanks for the patches!  This is the sort of tool I wish I had more time to work on.  I note that Jane Street developed a similar PPX rewriter a year or so after my initial release and I never figured I'd be able to really reason about it and keep up.  Huzzah for community contribution!

I'm assuming you have some interest in using the library considering your contributions.  May I ask for a link if one is available?

**Comment by hcarty** [comment]
Happy to contribute where I can!  I don't have anything public at the moment, sadly.  If that changes I'll try to pass a link along!

I like the idea of Jane St's ppx_let but it somewhat requires using their suite of libraries.  My projects aren't using base/core/etc, at least for now, so it's not a good fit.

**Pull request merged**
