### PR TITLE
Port to jbuilder and ocaml-migrate-parsetree

### PR DESCRIPTION
**Pull request by hcarty**
Works in my (basic) local testing.

### CODE REVIEW

**Comment by zepalmer** [comment]
Wow!  This is quite nice; thank you!

Before I accept the request, I wanted to ask a couple clarifying questions:

1. I've just read about `ocaml-migrate-parsetree` but I'm unfamiliar with how it works.  May I ask you to summarize the semantics of what you've changed?  I see that the version 4.04 is specifically named here.  Is that claiming that we're generating ASTs for OCaml 4.04?

2. Why does this pull request remove the `.merlin` file from the repository?

Again: thanks for this port.  I've been meaning to look into jbuilder as I've heard that the community is moving in that direction but I simply haven't had the time yet.  This will be quite instructive!

**Comment by hcarty** [comment]
Good questions!  I pushed a few new commits to clean things up a bit.

1. `ocaml-migrate-parsetree` translates the active compiler's AST (say, 4.02.3 for example) version into the AST version specified by in the code (4.06 as of my last commit).  The original PR was targeting 4.04 and my last commit (09a42db) bumped it to 4.06.  The goal is to be somewhat protected from AST changes in new OCaml releases.  If an AST fragment is used in ocaml-monadic which is not supported by the active compiler then ocaml-migrate-parsetree will fail stating that it doesn't have the means to migrate that code.  That should not be an issue for ocaml-monadic, at least in its current state!
2. `jbuilder` automatically generates `.merlin` files!  So they don't need to be tracked in git any longer.

Please let me know if you have any other questions or concerns!  I also added the `--dev` flag to the `all` (default) and `test` targets in the `Makefile` which turns on more warnings.  The only complaints it had were a few usused variables which were cleaned up with a `_` prefix.

**Comment by hcarty** [comment]
The last commit adds a proper `make repl` target which will start a utop session with the local source tree's `ocaml-monadic` ppx already loaded.

**Comment by zepalmer** [comment]
Thanks for the answers; that clears up a lot!  I've made a few changes to the documentation.

If I understand your description of `ocaml-migrate-parsetree` correctly, it sounds like `ocaml-monadic` will always want to use the current AST version provided by the compiler for its translation.  For instance, a `let%bind` expression is actually `[%bind let ...]` and so the user's code being bound to a variable will wind up getting fed through the migration.  If we don't keep the version matching the current compiler, then a user who writes theoretical 4.07-specific code in the future wouldn't be able to use `ocaml-monadic` until we'd updated it, correct?

If the above is true, I remember seeing something about `Migrate_parsetree.Versions.current`; would that be appropriate here?

Thanks again for the PR!

**Comment by hcarty** [comment]
I think you're correct about code using 4.07-specific features not working with a 4.06-based OMP module.  I just tested by using the 4.02 OMP+ppx_tools_versioned in a simple ppx then applying it to some code using inline modules (a 4.03+ feature).  Sure enough that failed with an error about the unsupported AST feature.

Unfortunately ppx_tools_versioned does not have `current` equivalent as far as I understand.  I think we'd need both OMP and ppx_tools_versioned to support a `current` equivalent for this to work.  I filed an [upstream issue](https://github.com/ocaml-ppx/ppx_tools_versioned/issues/5) to see if this would be a worthwhile addition.

**Comment by hcarty** [comment]
And thanks for the doc fixes and cleanup!  Sorry I missed those in the PR.

**Pull request merged**
